# settings.yaml

# --- Data Paths ---
dataset_path: "./dataset/raw-data"
processed_path: "./dataset/processed"
model_output_path: ./models/
data_yaml: ./dataset/processed/data.yaml

# --- Class & Color Mapping ---
class_names:
  0: light_blue
  1: dark_blue
  2: other
class_map:
  light_blue: 0
  dark_blue: 1
  other: 2

# --- Preprocessing (Versi V4) ---
hsv_thresholds:
  light_blue_h: [75, 110]
  dark_blue_h: [110, 130]
  min_saturation: 30
  min_value: 70
train_val_split: 0.8

# --- Training Parameters ---
model_name: yolov8n.pt
epochs: 50
batch_size: 16
learning_rate: 0.001
img_size: 640

# --- WandB ---
wandb_project: "ada-mata-bsort"
wandb_entity: "fazrah16mewar-123"